name: Test Cases with docker and code quality
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: https://index.docker.io/v1/

      - name: install dependencies
        run: pip install pytest

      - name: Test with pytest
        run: pytest test.py

      - name: Build Docker image
        run: docker buildx build -t anshussain1539/MLOps_project --push .
